---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds/
  - operator/
  - webhook/

images:
  - name: prometheus-operator
    newName: quay.io/prometheus-operator/prometheus-operator
    newTag: "v0.84.1"
  - name: prometheus-certs
    newName: jettech/kube-webhook-certgen
    newTag: "v1.5.2"

...
