---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: prometheus-selfsigned
spec:
  selfSigned: {}

...
---
apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: prometheus-webhook

spec:
  secretName: prometheus-webhook

  issuerRef:
    name: prometheus-selfsigned
    kind: Issuer
    group: cert-manager.io

  dnsNames:
    - "prometheus-operator"

...
