---
apiVersion: cert-manager.io/v1
kind: Issuer

metadata:
  name: prometheus-selfsigned
  labels:
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/component: webhook

spec:
  selfSigned: {}

...
---
apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: prometheus-webhook
  labels:
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/component: webhook

spec:
  secretName: prometheus-webhook

  issuerRef:
    name: prometheus-selfsigned
    kind: Issuer
    group: cert-manager.io

  dnsNames:
    - "prometheus-operator"

...
