---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: prometheus-webhook
  labels:
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/component: webhook

rules:
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - "validatingwebhookconfigurations"
    verbs:
      - "get"
      - "update"

...
