---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration

metadata:
  name: prometheus-webhook
  annotations:
    cert-manager.io/inject-ca-from: prometheus-webhook

webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: prometheus-operator
        path: /admission-prometheusrules/mutate
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: prometheusrulemutate.monitoring.coreos.com
    rules:
      - apiGroups:
          - monitoring.coreos.com
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
        resources:
          - prometheusrules
    sideEffects: None
    timeoutSeconds: 10

...
