---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: prometheus-webhook
  labels:
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/component: webhook

rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "create"

...
