---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: prometheus-webhook
  labels:
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/component: webhook

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-webhook

subjects:
  - kind: ServiceAccount
    name: prometheus-webhook

...
